[build]
  functions = "netlify/functions" # Specifies the directory for serverless functions
  publish = "dist" # Specifies the directory to deploy
  command = "npm run build" # Build command to run
  environment = {
    NODE_ENV = "production" # Example environment variable
  }

# Additional configurations for different contexts
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "staging"

[context.build.environment]
  NODE_ENV = "development"

# Example plugin configuration, uncomment and adjust as needed
#[plugins]
#  package = "@netlify/plugin-my-framework" # Uncomment and replace with your specific plugin
