[build]
  functions = "netlify/functions"
  publish = "dist"
  command = "npm run build"
  environment = { # Start of the environment block
    NODE_ENV = "production"
  } # End of the environment block
