### Create a report
POST http://localhost:3000/reports
Content-Type: application/json

{
    "price": 20000,
    "make": "ford",
    "model": "mustang",
    "year": 2006,
    "lat": 45,
    "lng": 45,
    "miles": 4500
}

### Update a report
PATCH http://localhost:3000/reports/3
Content-Type: application/json

{
    "approved": true
}

### Set color in session
GET http://localhost:3000/reports?make=ford&model=mustang&year=2006&lat=45&lng=45&miles=2000