### Create a report
POST http://localhost:3000/reports
Content-Type: application/json

{
    "price": 20000,
    "make": "Toyota",
    "model": "X korolla",
    "year": 2005,
    "lat": 0,
    "lng": 0,
    "miles": 5000
}

### Update a report
PATCH http://localhost:3000/reports/3
Content-Type: application/json

{
    "approved": true
}

### Set color in session
GET http://localhost:3000/reports?make=Toyota&model=corolla&year=2005&lat=0&lng=0&miles=2000